module.exports = {

    /* Creates the appended URI, in order to be able to run the Fetch call correctly, 
    and return the results of the character and comics/series. The API Fetch call MUST contain the Public Key, 
    as generated by creating a Developer account */

    publicKey: function () {
        return '5ef86689af1d8abd822d2eeb00844eda';
    },

    appendParam: function (uriString, paramName, paramValue) {
        if (uriString.includes('?')) {
            return uriString + '&' + paramName + '=' + encodeURI(paramValue);
        } else {
            return uriString + '?' + paramName + '=' + encodeURI(paramValue);
        }
    },

    urlWithPublicKey: function (uriString) {
        return this.appendParam(uriString, 'apikey', this.publicKey());
    }
};